### ISSUE TITLE
support for structs

### ISSUE THREAD

**Issue by ErikLambrechts** [Badhi/nvim-treesitter-cpp-tools#10]
Thanks, for the nice tool. Would it be possible to add the same functionality for structs?

**Comment by Badhi** [comment]
Thanks for the suggestion. Yes I will try to get it working for structs as well

**Comment by Badhi** [comment]
Please give it a try now. It should be working for structs (and unions) as well now

**Comment by ErikLambrechts** [comment]
work great thanks
