### ISSUE TITLE
Error: attempt to index local 'config'

### ISSUE THREAD

**Issue by luator** [Badhi/nvim-treesitter-cpp-tools#26]
Hello,

I added the plugin to my config using the example config from the README.  Now, I get this error whenever I start nvim:
```
Error detected while processing /home/felixwidmaier/.local/share/nvim/plugged/nvim-treesitter-cpp-tools/plugin/nt-cpp
-tools.vim:
line    1:
E5108: Error executing lua ...m/plugged/nvim-treesitter-cpp-tools/lua/nt-cpp-tools.lua:56: attempt to index local 'co
nfig' (a nil value)
stack traceback:
        ...m/plugged/nvim-treesitter-cpp-tools/lua/nt-cpp-tools.lua:56: in function 'init'
        [string ":lua"]:1: in main chunk
```
Any idea what is wrong?

**Comment by Badhi** [comment]
Thanks for the bug report and workaround. Yes, seems like there is a plugin load ordering randomness which causes this plugin to load before the tree-sitter plugin. Therefore, the config details are not yet available at the time of this plugin initialization. I still dont have a solution for this. Will look into it as soon as I have time.

In the meantime, @Frydac's workaround works as long as you do not use `custom_define_class_function_commands` option in the config

**Comment by Badhi** [comment]
Raised this issue to the tree-sitter plugin and the [solution](https://github.com/nvim-treesitter/nvim-treesitter/discussions/4465) they provided is to extract the configuration table to a standalone table rather than being part of the `treesitter.config`.
