### ISSUE TITLE
TSCppMakeConcreteClass not work

### ISSUE THREAD

**Issue by paopaol** [Badhi/nvim-treesitter-cpp-tools#28]
TSCppMakeConcreteClass not work

E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 144 for language cpp
stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
	.../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:300: in function 'run'

**Comment by Badhi** [comment]
Hi @paopaol , Thanks for the bug report. I could reproduce the issue and will fix it as soon as possible

**Comment by Badhi** [comment]
Hi @paopaol , Sorry for the really late fix, was a bit busy lately. I've submitted the fix. Could you please verify?
