### ISSUE TITLE
Error: no paraser for 'cpp' language

### ISSUE THREAD

**Issue by PEKEW** [Badhi/nvim-treesitter-cpp-tools#29]
I encountered an issue while using this plugin:

![image](https://github.com/Badhi/nvim-treesitter-cpp-tools/assets/98371836/3a0b0804-a04d-4ed2-873f-6baf689837c2)

My configuration is based on LazyVim, and I apologize for not being familiar with NVIM. It's possible that I missed some configurations.

**Comment by Badhi** [comment]
Try
`:TSInstall cpp`
to install treesitter parser for c++

**Comment by PEKEW** [comment]
> Try `:TSInstall cpp` to install treesitter parser for c++

Thx !
