### ISSUE TITLE
TSCppDefineClassFunc does nothing if no function is selected

### ISSUE THREAD

**Issue by Shatur** [Badhi/nvim-treesitter-cpp-tools#4]
**Steps to reproduce**

1. Navigate to any function declaration, stay in normal mode.
2. `:TSCppDefineClassFunc`

**Expected behavior**

Definition for function under cursor.

**Current behavior**

The cursor moves to the beginning of the file, but there is no preview. When you confirm your selection, the file is modified, but the definition is not created.

**Comment by Badhi** [comment]
Added the feature to create class functions in normal mode. Please sync the master (1f61581) and give a try
