### ISSUE TITLE
Template class in a same template class

### ISSUE THREAD

**Issue by iHapiW** [Badhi/nvim-treesitter-cpp-tools#42]
I'm creating a `DynArr` template class with T as its typename. and i have an `Iterator` class defined in it which has to have T as its typename.
I cant add the `template <typename T>` before Iterator class definition because it shadows the prior. and if i dont add it, the plugin wont work and would give this error:
```
E5108: Error executing lua .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:304: attempt to co
ncatenate field 'class_template_statement' (a nil value)
stack traceback:
        .../nvim-treesitter-cpp-tools/lua/nt-cpp-tools/internal.lua:304: in function 'run'
        [string ":lua"]:1: in main chunk
```

to reproduce:
create a header file and paste this into there:
```cpp
#pragma once

#include <stdlib.h>

#include <initializer_list>

template <typename T>
class DynArr {
public:
    class Iterator {
    public:
        Iterator(T* ptr);

    private:
        T* m_ptr{nullptr};
    };
    // Constructors
    DynArr() = default;
    DynArr(std::initializer_list<T> list);

    // Methods
    std::size_t size() const;

    // Operators
    const T& operator[](std::size_t i) const;
    T& operator[](std::size_t i);

private:
    T* m_arr{nullptr};
    std::size_t m_size{};
};
```

then try to call TSCppDefineClassFunc on the Iterator consturctor

**Comment by Badhi** [comment]
Thanks for filing the issue. yes seems like having a templated class as the parent doesn't work. Let me get it fixed

**Comment by Badhi** [comment]
please sync and retry now
